# Generated by Django 4.2.5 on 2023-10-09 18:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='description',
            field=models.TextField(
                blank=True, default=None, null=True, verbose_name='description'
            ),
        ),
        migrations.AlterField(
            model_name='pagefollow',
            name='deleted_at',
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                default=None,
                editable=False,
                null=True,
                verbose_name='deletion date and time',
            ),
        ),
        migrations.AlterField(
            model_name='pagelabel',
            name='deleted_at',
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                default=None,
                editable=False,
                null=True,
                verbose_name='deletion date and time',
            ),
        ),
        migrations.AlterField(
            model_name='pagelabeltype',
            name='deleted_at',
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                default=None,
                editable=False,
                null=True,
                verbose_name='deletion date and time',
            ),
        ),
        migrations.AlterField(
            model_name='pagelike',
            name='deleted_at',
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                default=None,
                editable=False,
                null=True,
                verbose_name='deletion date and time',
            ),
        ),
        migrations.AlterField(
            model_name='pageview',
            name='deleted_at',
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                default=None,
                editable=False,
                null=True,
                verbose_name='deletion date and time',
            ),
        ),
    ]
