# Generated by Django 4.2.5 on 2023-10-15 08:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagefollow',
            name='page',
        ),
        migrations.RemoveField(
            model_name='pagefollow',
            name='user',
        ),
        migrations.RemoveField(
            model_name='pagelike',
            name='page',
        ),
        migrations.RemoveField(
            model_name='pagelike',
            name='user',
        ),
        migrations.RemoveField(
            model_name='pagereaction',
            name='page',
        ),
        migrations.RemoveField(
            model_name='pagereaction',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='pagereaction',
            name='user',
        ),
        migrations.RemoveField(
            model_name='pageshow',
            name='page',
        ),
        migrations.RemoveField(
            model_name='pageshow',
            name='user',
        ),
        migrations.RemoveField(
            model_name='pageview',
            name='page',
        ),
        migrations.RemoveField(
            model_name='pageview',
            name='user',
        ),
        migrations.RemoveConstraint(
            model_name='pagelabel',
            name='unique_name_per_type',
        ),
        migrations.AlterField(
            model_name='applicationtoken',
            name='expires_at',
            field=models.DateTimeField(
                blank=True, default=None, null=True, verbose_name='expiry date and time'
            ),
        ),
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.SlugField(
                blank=True,
                default=None,
                max_length=64,
                null=True,
                verbose_name='page slug',
            ),
        ),
        migrations.AlterField(
            model_name='pagelabeltype',
            name='slug',
            field=models.SlugField(max_length=32, verbose_name='type slug'),
        ),
        migrations.AlterField(
            model_name='pagemetaitem',
            name='key',
            field=models.SlugField(max_length=64, verbose_name='meta key'),
        ),
        migrations.AlterField(
            model_name='servicetoken',
            name='expires_at',
            field=models.DateTimeField(
                blank=True, default=None, null=True, verbose_name='expiry date and time'
            ),
        ),
        migrations.AddConstraint(
            model_name='page',
            constraint=models.UniqueConstraint(
                fields=('slug', 'application'), name='unique_page_slug_per_application'
            ),
        ),
        migrations.AddConstraint(
            model_name='pagelabel',
            constraint=models.UniqueConstraint(
                fields=('type', 'name'), name='unique_pagelabel_name_per_type'
            ),
        ),
        migrations.AddConstraint(
            model_name='pagelabeltype',
            constraint=models.UniqueConstraint(
                fields=('slug', 'application'),
                name='unique_pagelabeltype_slug_per_application',
            ),
        ),
        migrations.AddConstraint(
            model_name='pagemetaitem',
            constraint=models.UniqueConstraint(
                fields=('key', 'page'), name='unique_pagemetaitem_key_per_page'
            ),
        ),
        migrations.DeleteModel(
            name='PageFollow',
        ),
        migrations.DeleteModel(
            name='PageLike',
        ),
        migrations.DeleteModel(
            name='PageReaction',
        ),
        migrations.DeleteModel(
            name='PageShow',
        ),
        migrations.DeleteModel(
            name='PageView',
        ),
    ]
