# Generated by Django 4.2.5 on 2023-10-15 10:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content', '0002_remove_pagefollow_page_remove_pagefollow_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentTheme',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name='uuid primary key',
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        verbose_name='creation date and time',
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        verbose_name='update date and time',
                    ),
                ),
                ('name', models.CharField(max_length=32, verbose_name='theme name')),
                (
                    'css',
                    models.TextField(
                        blank=True, default=None, null=True, verbose_name='theme css'
                    ),
                ),
                (
                    'url',
                    models.URLField(
                        blank=True,
                        default=None,
                        null=True,
                        verbose_name='theme style sheet url',
                    ),
                ),
                (
                    'owner',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='+',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='owner',
                    ),
                ),
                (
                    'service',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='content.service',
                        verbose_name='service',
                    ),
                ),
            ],
            options={
                'verbose_name': 'content theme',
                'verbose_name_plural': 'content themes',
                'db_table': 'launchbox_content_theme',
                'ordering': ('-created_at',),
            },
        ),
    ]
