# Generated by Django 4.2.5 on 2023-10-09 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('content', '0002_page_description_alter_pagefollow_deleted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='labels',
            field=models.ManyToManyField(
                blank=True,
                related_name='pages',
                through='content.PageLabeling',
                to='content.pagelabel',
                verbose_name='labels',
            ),
        ),
        migrations.AlterField(
            model_name='pagelabeling',
            name='label',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='+',
                to='content.pagelabel',
                verbose_name='label',
            ),
        ),
        migrations.AlterField(
            model_name='pagelabeling',
            name='page',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='+',
                to='content.page',
                verbose_name='page',
            ),
        ),
    ]
