# Generated by Django 4.2.5 on 2023-10-10 02:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('content', '0003_page_labels_alter_pagelabeling_label_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagemetaitem',
            name='key',
            field=models.SlugField(
                default='', max_length=64, unique=True, verbose_name='meta key'
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.SlugField(
                blank=True,
                default=None,
                max_length=64,
                null=True,
                unique=True,
                verbose_name='page slug',
            ),
        ),
    ]
