# Generated by Django 4.2.5 on 2023-10-15 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('content', '0003_contenttheme'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='theme',
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='content.contenttheme',
                verbose_name='theme',
            ),
        ),
        migrations.AddField(
            model_name='content',
            name='title',
            field=models.CharField(
                blank=True,
                default=None,
                max_length=32,
                null=True,
                verbose_name='content title',
            ),
        ),
    ]
